name: Docker image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-18.04
    strategy:
      matrix:
        version: ["0.4.10"]

    steps:
    - name: Set up multiarch
      uses: docker/setup-qemu-action@v1
    - name: Set up BuildX
      uses: docker/setup-buildx-action@v1
    - uses: actions/checkout@v2
    - name: Docker login
      run: |
        echo ${GHCR_KEY} | docker login -u ${GITHUB_ACTOR} --password-stdin ghcr.io
        echo ${DOCKER_HUB_KEY} | docker login -u cmbdevopsbot --password-stdin
      env:
        GHCR_KEY: ${{ secrets.GHCR_KEY }}
        DOCKER_HUB_KEY: ${{ secrets.DOCKER_HUB_KEY }}
    - name: Build/push Docker image
      run: | 
        docker buildx build --push --platform linux/amd64,linux/arm64,linux/386,linux/arm,linux/ppc64le,linux/s390x . \
          --build-arg version=${{ matrix.version }} --file Dockerfile \
          --tag ghcr.io/combinationab/grpc-health-probe:${{ matrix.version }} \
          --tag combination/grpc-health-probe:${{ matrix.version }}
